import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACBiBG1/HMZyWEfBH6vI+UEshiOvK9cNaSFwP3x99dTR8gAAAJBpPMQxaTzE
MQAAAAtzc2gtZWQyNTUxOQAAACBiBG1/HMZyWEfBH6vI+UEshiOvK9cNaSFwP3x99dTR8g
AAAEC6L0oSKVzDlT7PEjxSYIADz3N6HRW4wUu5OAAkrReKgGIEbX8cxnJYR8Efq8j5QSyG
I68r1w1pIXA/fH311NHyAAAABm15LWtleQECAwQFBgc=
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
